apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: discord-bot-dev

resources:
  - ../../base

namePrefix: ""
nameSuffix: ""

commonLabels:
  environment: dev

images:
  - name: docker.toastedbytes.com/discord-ai-bot
    newTag: dev-latest

patches:
  - target:
      kind: Namespace
      name: discord-bot
    patch: |
      - op: replace
        path: /metadata/name
        value: discord-bot-dev
