apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: discord-bot

resources:
  - namespace.yaml
  - deployment.yaml
  - secret.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
