apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: discord-bot-prod

resources:
  - ../../base

namePrefix: ""
nameSuffix: ""

commonLabels:
  environment: prod

images:
  - name: docker.toastedbytes.com/discord-ai-bot
    newTag: prod-latest

patches:
  - target:
      kind: Namespace
      name: discord-bot
    patch: |
      - op: replace
        path: /metadata/name
        value: discord-bot-prod

  - target:
      kind: Deployment
      name: discord-bot
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
